# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sat Apr 23 00:16:31 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MotorsBox = QtGui.QGroupBox(self.centralwidget)
        self.MotorsBox.setObjectName(_fromUtf8("MotorsBox"))
        self.gridLayout = QtGui.QGridLayout(self.MotorsBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MotorsFront = QtGui.QSlider(self.MotorsBox)
        self.MotorsFront.setMinimum(0)
        self.MotorsFront.setMaximum(255)
        self.MotorsFront.setOrientation(QtCore.Qt.Vertical)
        self.MotorsFront.setObjectName(_fromUtf8("MotorsFront"))
        self.gridLayout.addWidget(self.MotorsFront, 1, 0, 1, 1)
        self.MotorsBack = QtGui.QSlider(self.MotorsBox)
        self.MotorsBack.setMinimum(0)
        self.MotorsBack.setMaximum(255)
        self.MotorsBack.setOrientation(QtCore.Qt.Vertical)
        self.MotorsBack.setObjectName(_fromUtf8("MotorsBack"))
        self.gridLayout.addWidget(self.MotorsBack, 1, 1, 1, 1)
        self.MotorsFrontLabel = QtGui.QLabel(self.MotorsBox)
        self.MotorsFrontLabel.setObjectName(_fromUtf8("MotorsFrontLabel"))
        self.gridLayout.addWidget(self.MotorsFrontLabel, 0, 0, 1, 1)
        self.MotorsBackLabel = QtGui.QLabel(self.MotorsBox)
        self.MotorsBackLabel.setObjectName(_fromUtf8("MotorsBackLabel"))
        self.gridLayout.addWidget(self.MotorsBackLabel, 0, 1, 1, 1)
        self.MotorsLeft = QtGui.QSlider(self.MotorsBox)
        self.MotorsLeft.setMinimum(0)
        self.MotorsLeft.setMaximum(255)
        self.MotorsLeft.setOrientation(QtCore.Qt.Vertical)
        self.MotorsLeft.setObjectName(_fromUtf8("MotorsLeft"))
        self.gridLayout.addWidget(self.MotorsLeft, 1, 2, 1, 1)
        self.MotorsRight = QtGui.QSlider(self.MotorsBox)
        self.MotorsRight.setMinimum(0)
        self.MotorsRight.setMaximum(255)
        self.MotorsRight.setOrientation(QtCore.Qt.Vertical)
        self.MotorsRight.setObjectName(_fromUtf8("MotorsRight"))
        self.gridLayout.addWidget(self.MotorsRight, 1, 3, 1, 1)
        self.MotorsRightLabel = QtGui.QLabel(self.MotorsBox)
        self.MotorsRightLabel.setObjectName(_fromUtf8("MotorsRightLabel"))
        self.gridLayout.addWidget(self.MotorsRightLabel, 0, 3, 1, 1)
        self.MotorsLeftLabel = QtGui.QLabel(self.MotorsBox)
        self.MotorsLeftLabel.setObjectName(_fromUtf8("MotorsLeftLabel"))
        self.gridLayout.addWidget(self.MotorsLeftLabel, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.MotorsBox)
        self.AccBox = QtGui.QGroupBox(self.centralwidget)
        self.AccBox.setObjectName(_fromUtf8("AccBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.AccBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.AccGetData = QtGui.QCheckBox(self.AccBox)
        self.AccGetData.setObjectName(_fromUtf8("AccGetData"))
        self.verticalLayout.addWidget(self.AccGetData)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.AccXDataLabel = QtGui.QLabel(self.AccBox)
        self.AccXDataLabel.setObjectName(_fromUtf8("AccXDataLabel"))
        self.gridLayout_2.addWidget(self.AccXDataLabel, 0, 0, 1, 1)
        self.AccYDataLabel = QtGui.QLabel(self.AccBox)
        self.AccYDataLabel.setObjectName(_fromUtf8("AccYDataLabel"))
        self.gridLayout_2.addWidget(self.AccYDataLabel, 0, 1, 1, 1)
        self.AccZDataLabel = QtGui.QLabel(self.AccBox)
        self.AccZDataLabel.setObjectName(_fromUtf8("AccZDataLabel"))
        self.gridLayout_2.addWidget(self.AccZDataLabel, 0, 2, 1, 1)
        self.AccXData = QtGui.QProgressBar(self.AccBox)
        self.AccXData.setMinimum(-128)
        self.AccXData.setMaximum(128)
        self.AccXData.setProperty(_fromUtf8("value"), 0)
        self.AccXData.setOrientation(QtCore.Qt.Vertical)
        self.AccXData.setFormat(_fromUtf8(""))
        self.AccXData.setObjectName(_fromUtf8("AccXData"))
        self.gridLayout_2.addWidget(self.AccXData, 1, 0, 1, 1)
        self.AccYData = QtGui.QProgressBar(self.AccBox)
        self.AccYData.setMinimum(-128)
        self.AccYData.setMaximum(128)
        self.AccYData.setProperty(_fromUtf8("value"), 0)
        self.AccYData.setOrientation(QtCore.Qt.Vertical)
        self.AccYData.setFormat(_fromUtf8(""))
        self.AccYData.setObjectName(_fromUtf8("AccYData"))
        self.gridLayout_2.addWidget(self.AccYData, 1, 1, 1, 1)
        self.AccZData = QtGui.QProgressBar(self.AccBox)
        self.AccZData.setMinimum(-128)
        self.AccZData.setMaximum(128)
        self.AccZData.setProperty(_fromUtf8("value"), 0)
        self.AccZData.setOrientation(QtCore.Qt.Vertical)
        self.AccZData.setFormat(_fromUtf8(""))
        self.AccZData.setObjectName(_fromUtf8("AccZData"))
        self.gridLayout_2.addWidget(self.AccZData, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.AccBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.MotorsFrontLabel.setBuddy(self.MotorsFront)
        self.MotorsBackLabel.setBuddy(self.MotorsBack)
        self.MotorsRightLabel.setBuddy(self.MotorsRight)
        self.MotorsLeftLabel.setBuddy(self.MotorsLeft)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.MotorsFront, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MotorsSetFront)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("AccXDataChanged(int)")), self.AccXData.setValue)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("AccYDataChanged(int)")), self.AccYData.setValue)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("AccZDataChanged(int)")), self.AccZData.setValue)
        QtCore.QObject.connect(self.MotorsBack, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MotorsSetBack)
        QtCore.QObject.connect(self.MotorsLeft, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MotorsSetLeft)
        QtCore.QObject.connect(self.MotorsRight, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MotorsSetRight)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.MotorsBox.setTitle(QtGui.QApplication.translate("MainWindow", "Motors", None, QtGui.QApplication.UnicodeUTF8))
        self.MotorsFrontLabel.setText(QtGui.QApplication.translate("MainWindow", "Front", None, QtGui.QApplication.UnicodeUTF8))
        self.MotorsBackLabel.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.MotorsRightLabel.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.MotorsLeftLabel.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.AccBox.setTitle(QtGui.QApplication.translate("MainWindow", "Accelerator", None, QtGui.QApplication.UnicodeUTF8))
        self.AccGetData.setText(QtGui.QApplication.translate("MainWindow", "Daten vom IC holen.", None, QtGui.QApplication.UnicodeUTF8))
        self.AccXDataLabel.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.AccYDataLabel.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.AccZDataLabel.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))

